services:
  psql:
    container_name: psql
    image: postgres:16
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    ports:
      - "5433:5432"
    volumes:
      - ./psql:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    command: ["postgres", "-c", "listen_addresses=*"]

  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090

  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,s3
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "./init-localstack.sh:/etc/localstack/init/ready.d/init-localstack.sh"
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  products:
    build: ./products
    environment:
      - DATABASE_URL=postgres://postgres:root@psql:5432/db
      - POSTGRES_HOST=psql
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
      - SQS_QUEUE_URL=http://localstack:4566/000000000000/products-events
      - SQS_ENDPOINT=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
    ports:
      - "3000:3000"
    depends_on:
      - psql
      - localstack

  notifications:
    build: ./notifications
    environment:
      - SQS_QUEUE_URL=http://localstack:4566/000000000000/products-events
      - SQS_ENDPOINT=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
    ports:
      - "3001:3001"
    depends_on:
      - localstack

volumes:
  psql: