global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'products'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3000']
  - job_name: 'notifications'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3001']

